version: '3.8'
services:
  dnd-scheduler:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite:/app/data/scheduler.db
      - HTTP_PORT=3000
      - RUST_LOG=info
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
